#!/usr/bin/env bash
# vim : ft=bash :

Me=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
Lib=$Me/var
Src=$Me/src

mkdir -p $Lib $Src

(cd $Src
for f in *.awk; do
    gawk '
     BEGIN { RS=""; FS="\n" }
     NR>1  { $0=  gensub( /\.([^0-9\\*\\$\\+])([a-zA-Z0-9_]*)/, 
                      "[\"\\1\\2\"]","g", $0) } 
           { print $0 "\n" } ' $f > $Lib/$f
done )

if [ -n "$1" ]; then
  if [ -t 0 ]
  then         AWKPATH="$Lib:./:$AWKPATH"  gawk $*
  else cat - | AWKPATH="$Lib:./:$AWKPATH"  gawk $*
  fi
fi
